name: Code Performance & Test Validation

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to install make
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'  # Specify the Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install

      # Set environment variables for database configuration
      - name: Set up database environment variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_HOSTNAME=${{ secrets.DB_HOSTNAME }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DEFAULT_DB=${{ secrets.DEFAULT_DB }}" >> $GITHUB_ENV

      # Run tests
      - name: Run tests
        run: |
          poetry run pytest --cov --cov-report=xml:coverage-service.xml -v
  
      - name: Upload coverage reports to Codecov
        run: |
          pip install codecov
          codecov --verbose -t ${{ secrets.CODECOV_TOKEN }} -n 'service'-${{ github.run_id }} -F service -f coverage-service.xml
